version: '3'

services:
  photo-gallery:
    build: photo_gallery_server/
    depends_on:
      - 'database'
    ports:
      - '3003:3003'

  photo-details:
    build: product-details-service/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  photo-proxy:
    build: photo-gallery-proxy/
    depends_on:
      - 'database'
    ports:
      - '3103:3103'

  database:
    image: mongo:latest
